### ISSUE TITLE
citus-11.1.4/src/include/pg_version_compat.h:59:1: error: redefinition of ‘RelationGetSmgr’

### ISSUE THREAD

**Issue by LGRwx** [citusdata/citus#7373]
when I wanner build the citus with my own postgresql, I get too much error information when I try to compile and build it, what the title said is just one of it ,my postgresql version is 14.10, I have get the version about the citus program with the PG internal, the version of citus10.2.0 start to support the PG14, the version of citus 11.1.3 start to support the PG15, and the version of citus 12.1.0 start to support the PG16, But I have try the version between 10.2.0 and 11.1.3, and the version from 11.1.3 to 12.1.0, to compile with my own PG14.10, and I get too much error information, such as: error: redefinition of ‘RelationGetSmgr’、error: too few arguments to function ‘ExecARDeleteTriggers’、error: ‘AUTHNAME’ undeclared (first use in this function); did you mean ‘ATTNAME’?
the machine I have used is centos7.x86_64, I download from the git , and I unzip it , and rhen enter the source code directory , I run the ./autogen.sh
./configure PG_CONFIG=/usr/local/PostgreSQL-natived/postgresql/bin/pg_config
make -j`nproc`
and then I get the error information about I have told you above.
hoping to get your reply about your experience or suggestions!
![Uploading errorinformation.png…]()

**Comment by onurctirtir** [comment]
This has been fixed as of 11.1.6.
