### ISSUE TITLE
Redefinition of typedef - Build fails on EL/OL 6

### ISSUE THREAD

**Issue by hanefi** [citusdata/citus#3107]
On OL/EL 6 build fails because of a redefinition of a typedef.

```
planner/shard_pruning.c:151: error: redefinition of typedef 'FunctionCallInfo'
/usr/pgsql-11/include/server/fmgr.h:38: note: previous declaration of 'FunctionCallInfo' was here
```

https://github.com/citusdata/citus/blob/e760dd69acd2c728e29148117136e72e9c27beeb/src/backend/distributed/planner/shard_pruning.c#L151

[fmgr.h:38](https://github.com/postgres/postgres/blob/e5b4926ef6110ef4f21c197d462097072d38b39d/src/include/fmgr.h#L38)

This change was introduced in https://github.com/citusdata/citus/pull/2844 and it seems like only these distributions have this issue.

For the whole CI output see [here](https://api.travis-ci.org/v3/job/597547463/log.txt) and [here](https://travis-ci.org/citusdata/packaging/jobs/597547465)

**Comment by marcocitus** [comment]
Fixed by #3154
