### PR TITLE
Add jobs to test builds on different distros (release-11.0)

### PR DESCRIPTION
**Pull request by gurkanindibay**
With this PR, citus code will be tested in all packaging environments.  Sometimes, there can be compile errors which blocks packaging and in this case unplanned delays may occur.
By testing the code in packaging environments, I'm aiming to detect any compilation errors before packaging.

Co-authored-by: Onur Tirtir <onurcantirtir@gmail.com>
Co-authored-by: Hanefi Onaldi <Hanefi.Onaldi@microsoft.com>

DESCRIPTION: PR description that will go into the change log, up to 78 characters

### CODE REVIEW

**Comment by gurkanindibay** [comment]
@JelteF the Openssl warnings are blocking this PR to be merged. Could you merge the PR (https://github.com/citusdata/citus/pull/6502)
