### PR TITLE
Support RETURNING

### LINKED ISSUE #242: Support RETURNING in modification commands
<a href="https://github.com/digi604"></img></a> **Issue by [digi604](https://github.com/digi604)**
_Thursday Jul 23, 2015 at 15:23 GMT_
_Originally opened as https://github.com/citusdata/pg_shard/issues/128_

----

Any query using the `RETURNING` clause produces the following error:

    NotSupportedError: cannot perform distributed planning for the given query
    DETAIL:  RETURNING clauses are not supported in distributed queries.

Can you add support for `RETURNING` clauses?

### PR DESCRIPTION
**Pull request by anarazel**
Most of the code changes aren't really about returning itself, but about making it easy to support RETURNING.  I've tried to break it down to individually review-able commits. There's one bigger commit "Combine router executor paths for select and modify commands." which I previously had split up further; I can do that again.

Fixes #242

### CODE REVIEW

**Comment by anarazel** [comment]
I think handling of node failures is the part requiring most testing, since I've whacked that around; and it's pretty much not covered in the regression tests.

**Comment by onderkalaci** [comment]
Thanks for splitting the commits, it was very useful.

I've one high-level question on the change. We execute the RETURNING on the workers, and use rows that return from one of the workers. 
Once we have `Evaluating functions on the master`, are we going to get `nextval()` from the workers or from the master when users issue `RETURNING` on a serial? If we are to use the worker sequences, would that become a problem when we DROP/CREATE the placements via shard rebalancer and/or `master_copy_shard_placement()`? 

Also, there seems to be a bug, which I couldn't find where to write on the changes, so I add to here. When we define cursors on a router query, I observe an unexpected behaviour once the data finishes on the cursor:

```SQL
SELECT *
		FROM multiple_hash
		WHERE category = '0'
		ORDER BY category;

 category | data 
----------+------
 0        | 1-1
 0        | 2-1
 0        | 3-1
 0        | 4-1
 0        | 5-1
 0        | 6-1
(6 rows)

-- now go with the cursors
BEGIN;
DECLARE test_cursor CURSOR FOR 
	SELECT *
		FROM multiple_hash
		WHERE category = '0'
		ORDER BY category;
FETCH FORWARD 5 test_cursor;
 category | data 
----------+------
 0        | 1-1
 0        | 2-1
 0        | 3-1
 0        | 4-1
 0        | 5-1
(5 rows)

 FETCH FORWARD 5 test_cursor;
 category | data 
----------+------
 0        | 6-1
(1 row)

FETCH FORWARD 5 test_cursor;
ERROR:  scan directions other than forward scans are unsupported
```

The scan direction is appeared as `NoMovementScanDirection`. On regular tables (or real-time executor), we don't hit the above error. Is this issue related to this PR?

File: src/backend/distributed/executor/multi_router_executor.c [hunk 1]
```diff
@@ -230,125 +285,150 @@ RouterExecutorRun(QueryDesc *queryDesc, ScanDirection direction, long count, Tas
...
- * sends the resulting tuples to the given destination receiver. If the query fails on a
- * given placement, the function attempts it on its replica.
+ * ReturnRowsFromTuplestore moves rows from a given tuplestore into a
+ * receiver. It performs the necessary limiting to support cursors.
  */
-static void
-ExecuteSingleShardSelect(QueryDesc *queryDesc, uint64 tupleCount, Task *task,
-						 EState *executorState, TupleDesc tupleDescriptor,
-						 DestReceiver *destination)
+static int64
```
Comment (onderkalaci) [inline src/backend/distributed/executor/multi_router_executor.c]: Minor: It looks like we need to return `uint`. Also, this function does not use `executorState` parameter. You may want to remove that.

File: src/backend/distributed/executor/multi_router_executor.c [hunk 2]
```diff
@@ -558,6 +594,62 @@ StoreQueryResult(PGconn *connection, TupleDesc tupleDescriptor,
 
 
 /*
+ * ConsumeQueryResult gets a query result from a connection, counting the rows
+ * and checking for errors, but otherwise discarding potentially returned
+ * rows.  Returns true if a non-errorr result has been returned, false if
```
Comment (onderkalaci) [inline src/backend/distributed/executor/multi_router_executor.c]: Very minor: errorr -> error

File: src/backend/distributed/executor/multi_router_executor.c [hunk 3]
```diff
@@ -200,24 +207,72 @@ RouterExecutorRun(QueryDesc *queryDesc, ScanDirection direction, long count, Tas
...
+
+		if (operation == CMD_INSERT || operation == CMD_UPDATE ||
+			operation == CMD_DELETE)
+		{
+			isModificationQuery = true;
+		}
+		else if (operation != CMD_SELECT)
+		{
+			ereport(ERROR, (errmsg("unrecognized operation code: %d",
+								   (int) operation)));
```
Comment (onderkalaci) [inline src/backend/distributed/executor/multi_router_executor.c]: Minor: We already have this check on `RouterExecutorRun() -> CommutativityRuleToLockMode()`. Should we keep it here as well?

File: src/backend/distributed/executor/multi_router_executor.c [hunk 4]
```diff
@@ -230,125 +285,150 @@ RouterExecutorRun(QueryDesc *queryDesc, ScanDirection direction, long count, Tas
...
+			queryOK = StoreQueryResult(routerState, connection, tupleDescriptor,
+									   &currentAffectedTupleCount);
 		}
 		else
 		{
-			ereport(WARNING, (errmsg("modified %d tuples, but expected to modify %d",
-									 currentAffectedTupleCount, affectedTupleCount),
-							  errdetail("modified placement on %s:%d",
-										nodeName, nodePort)));
+			queryOK = ConsumeQueryResult(connection, &currentAffectedTupleCount);
```
Comment (onderkalaci) [inline src/backend/distributed/executor/multi_router_executor.c]: Should we use another variable then `queryOK` for `StoreQueryResult()` and `ConsumeQueryResult()`? Maybe `resulsOK` ?

File: src/backend/distributed/executor/multi_router_executor.c [hunk 5]
```diff
@@ -230,125 +285,150 @@ RouterExecutorRun(QueryDesc *queryDesc, ScanDirection direction, long count, Tas
...
-		currentAffectedTupleCount = pg_atoi(currentAffectedTupleString, sizeof(int32), 0);
-
-		if ((affectedTupleCount == -1) ||
-			(affectedTupleCount == currentAffectedTupleCount))
+		/*
+		 * If caller is interested, store query results the first time
+		 * through. The output of the query's execution on other shards is
+		 * discarded if we run there (because it's a modification query).
+		 */
+		if (!gotResults && expectResults)
```
Comment (onderkalaci) [inline src/backend/distributed/executor/multi_router_executor.c]: I think the word `results` a bit confusing. Instead of `gotResults` and `expectResults`, using `receiviedTuples` and `expectTuples` may look better. What do you think?

File: src/backend/distributed/executor/multi_router_executor.c [hunk 6]
```diff
@@ -180,6 +184,9 @@ RouterExecutorRun(QueryDesc *queryDesc, ScanDirection direction, long count, Tas
 	EState *estate = queryDesc->estate;
 	CmdType operation = queryDesc->operation;
 	MemoryContext oldcontext = NULL;
+	DestReceiver *destination = queryDesc->dest;
+	MaterialState *routerState = (MaterialState *) queryDesc->planstate;
+	bool sendTuples = operation == CMD_SELECT || queryDesc->plannedstmt->hasReturning;
```
Comment (onderkalaci) [inline src/backend/distributed/executor/multi_router_executor.c]: Minor: Is it `sendTuples` or, `receiveTuples` would fit better? 
Plus, I'd prefer to have an explicit `if` to assign the value to the variable. But, feel free to overlook this comment.

File: src/backend/distributed/executor/multi_router_executor.c [hunk 7]
```diff
@@ -200,24 +207,72 @@ RouterExecutorRun(QueryDesc *queryDesc, ScanDirection direction, long count, Tas
...
-	else if (operation == CMD_SELECT)
+
+	/*
+	 * If query has not yet been executed, do so now. The main reason why the
+	 * query might already have been executed is cursors.
+	 */
+	if (!routerState->eof_underlying)
+	{
+		bool resultsOK = false;
+		bool isModificationQuery = false;
```
Comment (onderkalaci) [inline src/backend/distributed/executor/multi_router_executor.c]: Minor again, the coding convention document suggests to avoid `Is`, instead use `modificationQuery`

File: src/test/regress/expected/multi_modifications.out [hunk 8]
```diff
@@ -335,9 +380,123 @@ SELECT symbol, bidder_id FROM limit_orders WHERE id = 246;
...
 UPDATE limit_orders SET placed_at = now() WHERE id = 246;
 ERROR:  functions used in modification queries on distributed tables must be marked IMMUTABLE
+-- even in RETURNING
+UPDATE limit_orders SET placed_at = placed_at WHERE id = 246 RETURNING NOW();
+ERROR:  functions used in modification queries on distributed tables must be marked IMMUTABLE
 -- cursors are not supported
 UPDATE limit_orders SET symbol = 'GM' WHERE CURRENT OF cursor_name;
 ERROR:  distributed modifications must target exactly one shard
+-- check that multi-row UPDATE/DELETEs with RETURNING work
+INSERT INTO multiple_hash VALUES ('0', '1');
```
Comment (onderkalaci) [inline src/test/regress/expected/multi_modifications.out]: I'd be nice to see an `UPSERT+RETURNING` test as well. But, that requires to have a unique  constraint on the partition key, which would make UPDATE tests less comprehensive with a single returning row. So, if you think it's not necessary, you can ignore this comment.

**Comment by anarazel** [comment]
> I've one high-level question on the change. We execute the RETURNING
> on the workers, and use rows that return from one of the workers.
> Once we have `Evaluating functions on the master`, are we going to get
> `nextval()` from the workers or from the master when users issue
> `RETURNING` on a serial? If we are to use the worker sequences, would
> that become a problem when we DROP/CREATE the placements via shard
> rebalancer and/or `master_copy_shard_placement()`?

It's going to come from the master.


> Also, there seems to be a bug, which I couldn't find where to write on
> the changes, so I add to here. When we define cursors on a router
> query, I observe an unexpected behaviour once the data finishes on the
> cursor:

Hm, that's rather likely not related to this change. Afaics that
behaviour already existed. We need a specific check for
NoMovementDirection, like in standard_ExecutorRun:
	/*
	 * run plan
	 */
	if (!ScanDirectionIsNoMovement(direction))
		ExecutePlan(estate,
					queryDesc->planstate,
					queryDesc->plannedstmt->parallelModeNeeded,
					operation,
					sendTuples,
					count,
					direction,
					dest);

File: src/backend/distributed/executor/multi_router_executor.c (hunk 1 above)
Comment (anarazel) [inline src/backend/distributed/executor/multi_router_executor.c]: > >   */
> > -static void
> > -ExecuteSingleShardSelect(QueryDesc *queryDesc, uint64 tupleCount, Task *task,
> > -						 EState *executorState, TupleDesc tupleDescriptor,
> > -						 DestReceiver *destination)
> > +static int64
> 
> Minor: It looks like we need to return `uint`.

There's a related discussion (#554), and it looks like it's going to be
int64.


> Also, this function does not use `executorState` parameter. You may
> want to remove that.

Sound sensible.

Comment (anarazel) [inline src/backend/distributed/executor/multi_router_executor.c]: > Also, this function does not use `executorState` parameter. You may want to remove that.

On second thought: It actually does use it?

File: src/backend/distributed/executor/multi_router_executor.c (hunk 3 above)
Comment (anarazel) [inline src/backend/distributed/executor/multi_router_executor.c]: On 2016-06-07 05:31:56 -0700, Önder Kalacı wrote:
> > +	 * query might already have been executed is cursors.
> > +	 */
> > +	if (!routerState->eof_underlying)
> > +	{
> > +		bool resultsOK = false;
> > +		bool isModificationQuery = false;
> > +
> > +		if (operation == CMD_INSERT || operation == CMD_UPDATE ||
> > +			operation == CMD_DELETE)
> > +		{
> > +			isModificationQuery = true;
> > +		}
> > +		else if (operation != CMD_SELECT)
> > +		{
> > +			ereport(ERROR, (errmsg("unrecognized operation code: %d",
> > +								   (int) operation)));
> 
> Minor: We already have this check on `RouterExecutorRun() -> CommutativityRuleToLockMode()`. Should we keep it here as well?

I think a bit of paranoia doesn't hurt here.

File: src/backend/distributed/executor/multi_router_executor.c (hunk 4 above)
Comment (anarazel) [inline src/backend/distributed/executor/multi_router_executor.c]: > >  		}
> >  		else
> >  		{
> > -			ereport(WARNING, (errmsg("modified %d tuples, but expected to modify %d",
> > -									 currentAffectedTupleCount, affectedTupleCount),
> > -							  errdetail("modified placement on %s:%d",
> > -										nodeName, nodePort)));
> > +			queryOK = ConsumeQueryResult(connection, &currentAffectedTupleCount);
> 
> Should we use another variable then `queryOK` for `StoreQueryResult()` and `ConsumeQueryResult()`? Maybe `resulsOK` ?

Why?

File: src/backend/distributed/executor/multi_router_executor.c (hunk 6 above)
Comment (anarazel) [inline src/backend/distributed/executor/multi_router_executor.c]: > > @@ -180,6 +184,9 @@ RouterExecutorRun(QueryDesc *queryDesc, ScanDirection direction, long count, Tas
> >  	EState *estate = queryDesc->estate;
> >  	CmdType operation = queryDesc->operation;
> >  	MemoryContext oldcontext = NULL;
> > +	DestReceiver *destination = queryDesc->dest;
> > +	MaterialState *routerState = (MaterialState *) queryDesc->planstate;
> > +	bool sendTuples = operation == CMD_SELECT || queryDesc->plannedstmt->hasReturning;
> 
> Minor: Is it `sendTuples` or, `receiveTuples` would fit better?

I think sending is correct. Also, it's what postgres uses.

File: src/backend/distributed/executor/multi_router_executor.c (hunk 7 above)
Comment (anarazel) [inline src/backend/distributed/executor/multi_router_executor.c]: > >  	}
> > -	else if (operation == CMD_SELECT)
> > +
> > +	/*
> > +	 * If query has not yet been executed, do so now. The main reason why the
> > +	 * query might already have been executed is cursors.
> > +	 */
> > +	if (!routerState->eof_underlying)
> > +	{
> > +		bool resultsOK = false;
> > +		bool isModificationQuery = false;
> 
> Minor again, the coding convention document suggests to avoid `Is`, instead use `modificationQuery`

I think that's bad here. modificationQuery sounds like it'd contain an
actual Query.

File: src/test/regress/expected/multi_modifications.out (hunk 8 above)
Comment (anarazel) [inline src/test/regress/expected/multi_modifications.out]: On 2016-06-07 05:47:49 -0700, Önder Kalacı wrote:
> >  -- cursors are not supported
> >  UPDATE limit_orders SET symbol = 'GM' WHERE CURRENT OF cursor_name;
> >  ERROR:  distributed modifications must target exactly one shard
> > +-- check that multi-row UPDATE/DELETEs with RETURNING work
> > +INSERT INTO multiple_hash VALUES ('0', '1');
> 
> I'd be nice to see an `UPSERT+RETURNING` test as well. But, that requires to have a unique  constraint on the partition key, which would make UPDATE tests less comprehensive with a single returning row. So, if you think it's not necessary, you can ignore this comment.

Good idea. We can do that on the limit_orders table.

**Comment by onderkalaci** [comment]
Just a note, the issue with Cursors I mentioned here doesn't show up on the `master` branch.

File: src/backend/distributed/executor/multi_router_executor.c (hunk 6 above)
Comment (onderkalaci) [inline src/backend/distributed/executor/multi_router_executor.c]: I thought that the master `receives` the tuples, that's why I suggested `receiveTuples`. But, `sending` is also fine if that's how postgres use.

File: src/backend/distributed/executor/multi_router_executor.c [hunk 9]
```diff
@@ -230,125 +285,150 @@ RouterExecutorRun(QueryDesc *queryDesc, ScanDirection direction, long count, Tas
 
 
 /*
- * ExecuteDistributedModify is the main entry point for modifying distributed
- * tables. A distributed modification is successful if any placement of the
- * distributed table is successful. ExecuteDistributedModify returns the number
- * of modified rows in that case and errors in all others. This function will
- * also generate warnings for individual placement failures.
+ * ExecuteTaskAndStoreResults executes the task on the remote node, retrieves
```
Comment (onderkalaci) [inline src/backend/distributed/executor/multi_router_executor.c]: ExecuteTaskAndStoreResults: It looks like the name and comment are obsolete. This function may not store the results anymore in case of `ConsumeQueryResults`. So, maybe change the name to `ExecuteRouterTask` or so?

File: src/backend/distributed/executor/multi_router_executor.c (hunk 4 above)
Comment (onderkalaci) [inline src/backend/distributed/executor/multi_router_executor.c]: Because we already used `queryOK` variable in the return value of `SendQueryInSingleRowMode()` and in an if statement. Using it for another purpose makes following the code a bit harder.

**Comment by onderkalaci** [comment]
@anarazel sorry for being late on the review. I added couple of notes for naming etc.. Other than that, the only issue I came across is the cursor issue mentioned above.

(As you mentioned node failure testing, I did lots of failure testing. All looks good.)

After you consider my comments, I'd like to do a final review and testing.

File: src/backend/distributed/executor/multi_router_executor.c (hunk 6 above)
Comment (anarazel) [inline src/backend/distributed/executor/multi_router_executor.c]: > > @@ -180,6 +184,9 @@ RouterExecutorRun(QueryDesc *queryDesc, ScanDirection direction, long count, Tas
> >  	EState *estate = queryDesc->estate;
> >  	CmdType operation = queryDesc->operation;
> >  	MemoryContext oldcontext = NULL;
> > +	DestReceiver *destination = queryDesc->dest;
> > +	MaterialState *routerState = (MaterialState *) queryDesc->planstate;
> > +	bool sendTuples = operation == CMD_SELECT || queryDesc->plannedstmt->hasReturning;
> 
> I thought that the master `receives` the tuples, that's why I suggested `receiveTuples`. But, `sending` is also fine if that's how postgres use.

But it's not about the number of tuples to receive from the workers (we
always receive all of them). It's about how many tuples we send to the client.

**Comment by anarazel** [comment]
Hi Onder. I can actually reproduce the CURSOR issue on master without any problem. Which isn't surprising, given that the relevant code didn't change. Could you verify that you can also reproduce it there, and open an issue if so?

**Comment by anarazel** [comment]
@onderkalaci I think this should be ready to go, what do you think?

**Comment by onderkalaci** [comment]
Hi @anarazel,
I partially reproduce the issue with cursors on the master branch. See the steps below:
```SQL
CREATE TABLE multiple_hash
(
	category text NOT NULL,
	data text NOT NULL 
);

INSERT INTO multiple_hash VALUES ('1', '1');
INSERT INTO multiple_hash VALUES ('1', '2');
INSERT INTO multiple_hash VALUES ('1', '3');
INSERT INTO multiple_hash VALUES ('1', '4');
INSERT INTO multiple_hash VALUES ('1', '5');
INSERT INTO multiple_hash VALUES ('1', '6');
INSERT INTO multiple_hash VALUES ('1', '7');

BEGIN;
DECLARE test_cursor CURSOR FOR 
    SELECT *
        FROM multiple_hash
        WHERE category = '0'
        ORDER BY category;

-- the same error exists on both `master` and `feature/returning` branches:
FETCH FORWARD 4 test_cursor;
FETCH FORWARD 4 test_cursor;
ERROR:  scan directions other than forward scans are unsupported


BEGIN;
DECLARE test_cursor CURSOR FOR 
    SELECT *
        FROM multiple_hash
        WHERE category = '1'
        ORDER BY category;

FETCH FORWARD 4 test_cursor;
FETCH FORWARD 4 test_cursor;

-- for the following commands error happens on `feature/returning` branch 
-- and not in `master` branch
FETCH FORWARD 4 test_cursor; 
FETCH FORWARD 4 test_cursor;
```
Though I couldn't locate exactly which change has led to the cursor issue,  postgres changes the scan direction [at this point](https://github.com/postgres/postgres/blob/c6dbf1fe79287291bc260cbc06b0de419d2a198c/src/backend/tcop/pquery.c#L931). And [portal->atEnd](https://github.com/postgres/postgres/blob/c6dbf1fe79287291bc260cbc06b0de419d2a198c/src/backend/tcop/pquery.c#L956) is set to true just below it. 

Reading [this](https://github.com/postgres/postgres/blob/c6dbf1fe79287291bc260cbc06b0de419d2a198c/src/backend/tcop/pquery.c#L917) comment makes me think that we should only error out when scan direction is `BackwardScanDirection` and allow both `NoMovementScanDirection` and `ForwardScanDirection` on router executor.

Since this patch introduces a small error that doesn't exist in `master`, I'm leaving the decision to you. I could either open another issue or we can fix it here at all.

File: src/backend/distributed/executor/multi_router_executor.c [hunk 10]
```diff
@@ -587,6 +612,93 @@ StoreQueryResult(PGconn *connection, TupleDesc tupleDescriptor,
...
+			int category = 0;
+			bool raiseError = false;
+
+			/*
+			 * If the error code is in constraint violation class, we want to
+			 * fail fast because we must get the same error from all shard
+			 * placements.
+			 */
+			category = ERRCODE_TO_CATEGORY(ERRCODE_INTEGRITY_CONSTRAINT_VIOLATION);
+			raiseError = SqlStateMatchesCategory(sqlStateString, category);
```
Comment (onderkalaci) [inline src/backend/distributed/executor/multi_router_executor.c]: While I was doing some failure testing, I realized that `sqlStateString` becomes empty when two nodes are down but the connections have already been cached (i.e., status == `PGRES_FATAL_ERROR`). This makes `SqlStateMatchesCategory()` to crash.

Steps to reproduce:
```SQL

CREATE TABLE multiple_hash 
( 
category text NOT NULL PRIMARY KEY, 
data text NOT NULL
);

SELECT master_create_distributed_table('multiple_hash', 'category', 'hash');
SELECT master_create_worker_shards('multiple_hash', 4, 2);

INSERT INTO multiple_hash VALUES ('1', '1');
```

```
-- now terminate both worker nodes nodes
/usr/local/pgsql/bin/pg_ctl -D /Users/onderkalaci/Documents/data_dir/worker_9700 -o "-p 9700" -l   /tmp/logfile_9700 stop -m f

/usr/local/pgsql/bin/pg_ctl -D /Users/onderkalaci/Documents/data_dir/worker_9701 -o "-p 9701" -l   /tmp/logfile_9701 stop -m f
```

```SQL
INSERT INTO multiple_hash VALUES ('1', '1');
WARNING:  terminating connection due to administrator command
CONTEXT:  while executing command on localhost:9701
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

Comment (onderkalaci) [inline src/backend/distributed/executor/multi_router_executor.c]: And, this behavior does not exist on `master` branch.

File: src/backend/distributed/executor/multi_router_executor.c [hunk 11]
```diff
@@ -534,10 +538,30 @@ StoreQueryResult(PGconn *connection, TupleDesc tupleDescriptor,
...
+			char *sqlStateString = PQresultErrorField(result, PG_DIAG_SQLSTATE);
+			int category = 0;
+			bool raiseError = false;
+
+			/*
+			 * If the error code is in constraint violation class, we want to
+			 * fail fast because we must get the same error from all shard
+			 * placements.
+			 */
+			category = ERRCODE_TO_CATEGORY(ERRCODE_INTEGRITY_CONSTRAINT_VIOLATION);
```
Comment (onderkalaci) [inline src/backend/distributed/executor/multi_router_executor.c]: I think that erroring out only for `ERRCODE_INTEGRITY_CONSTRAINT_VIOLATION` may lead to some cases where Citus marks placements inactive unnecessarily. For instance, if the error code is `ERRCODE_DIVISION_BY_ZERO` we got into this situation. 
Here are the steps:
```SQL

CREATE TABLE multiple_hash
(
	category text NOT NULL,
	data text NOT NULL 
);
SELECT master_create_distributed_table('multiple_hash', 'category', 'hash');
SELECT master_create_worker_shards('multiple_hash', 4, 2);

select * from pg_dist_shard_placement ;
 shardid | shardstate | shardlength | nodename  | nodeport 
---------+------------+-------------+-----------+----------
  102049 |          1 |           0 | localhost |     9700
  102049 |          1 |           0 | localhost |     9701
  102050 |          1 |           0 | localhost |     9701
  102050 |          1 |           0 | localhost |     9700
  102051 |          1 |           0 | localhost |     9700
  102051 |          1 |           0 | localhost |     9701
  102052 |          1 |           0 | localhost |     9701
  102052 |          1 |           0 | localhost |     9700
(8 rows)

-- insert a single value
INSERT INTO multiple_hash VALUES ('1', '1');

-- do a returning where we end-up with division by zero error
update multiple_hash SET data = (5 / (category::int - 1)) where category = '1' RETURNING *;
WARNING:  division by zero
CONTEXT:  while executing command on localhost:9701
WARNING:  division by zero
CONTEXT:  while executing command on localhost:9700
 category | data 
----------+------
(0 rows)

-- select again placement table
select * from pg_dist_shard_placement ;
 shardid | shardstate | shardlength | nodename  | nodeport 
---------+------------+-------------+-----------+----------
  102045 |          1 |           0 | localhost |     9700
  102045 |          1 |           0 | localhost |     9701
  102046 |          1 |           0 | localhost |     9701
  102047 |          1 |           0 | localhost |     9700
  102047 |          1 |           0 | localhost |     9701
  102048 |          1 |           0 | localhost |     9701
  102048 |          1 |           0 | localhost |     9700
  102046 |          3 |           0 | localhost |     9700
(8 rows)

```
Not that this doesn't happen without returning statement. I think the reason is that `StoreQueryResult()` returns true and  `ConsumeQueryResult()` returns false in the above case.

File: src/backend/distributed/executor/multi_router_executor.c (hunk 10 above)
Comment (anarazel) [inline src/backend/distributed/executor/multi_router_executor.c]: A slight change in your recipe shows the same result in master. If you kill -9/use -m immediate, instead of a normal restart, the same crash happens in master.  I opened #634 for that issue.  I think we just need a NULL check in SqlStateMatchesCategory().

File: src/backend/distributed/executor/multi_router_executor.c (hunk 11 above)
Comment (anarazel) [inline src/backend/distributed/executor/multi_router_executor.c]: I think that's a straight-forward bug in StoreQueryResult(). It mistakenly returns true in cases it clearly shouldn't. After doing that, the problem is gone. Nice catch!

**Comment by anarazel** [comment]
On 2016-06-28 04:46:24 -0700, Önder Kalacı wrote:
> Since this patch introduces a small error that doesn't exist in `master`, I'm leaving the decision to you. I could either open another issue or we can fix it here at all.

I don't think this has anything to do with the patch, the conditions
how the bug is triggered differe slightly, but it's clearly a
pre-existing bug.  I opened a separate issue for it (#635).

**Comment by anarazel** [comment]
I pushed two fixups (which will be squashed before merge), first adding a regression test showing the bug, and then a fix.

File: src/backend/distributed/executor/multi_router_executor.c [hunk 12]
```diff
@@ -575,14 +606,106 @@ StoreQueryResult(PGconn *connection, TupleDesc tupleDescriptor,
...
+			char *currentAffectedTupleString = PQcmdTuples(result);
+			int64 currentAffectedTupleCount = 0;
+
+			scanint8(currentAffectedTupleString, false, &currentAffectedTupleCount);
+			Assert(currentAffectedTupleCount >= 0);
+
+#if (PG_VERSION_NUM < 90600)
+
+			/* before 9.6, PostgreSQL used a uint32 for this field, so check */
+			Assert(currentAffectedTupleCount <= PG_UINT32_MAX);
```
Comment (onderkalaci) [inline src/backend/distributed/executor/multi_router_executor.c]: Well, this line does not compile on 9.4.6. How could travis pass the tests :)

```
executor/multi_router_executor.c:695:40: error: use of undeclared identifier 'PG_UINT32_MAX'
                        Assert(currentAffectedTupleCount <= PG_UINT32_MAX);
```

Comment (onderkalaci) [inline src/backend/distributed/executor/multi_router_executor.c]: Well, this line does not compile on 9.4.6. How could travis pass the tests :)

```
executor/multi_router_executor.c:695:40: error: use of undeclared identifier 'PG_UINT32_MAX'
                        Assert(currentAffectedTupleCount <= PG_UINT32_MAX);
```

**Comment by onderkalaci** [comment]
Hi @anarazel ,

I only want to ask you about my comment on the `ExecuteTaskAndStoreResults()` function (it's name and function comment). I still think that my comment is still valid. What do you think?

Other than that, as I noted, a single line does not compile on 9.4.6 when asserts are enabled. After the code compiles, I'll run check-full on 9.4.6, and then it's a :shipit:

**Comment by anarazel** [comment]
I don't really agree. Your suggested function name leaves the separation of concerns between RouterExecutorStart and ExecuteRouterTasks less clear imo.  And not having any rows to return is still computing the return value.  I'll update the comment though.

**Comment by anarazel** [comment]
@onderkalaci I've reworded the comment. If you're not happy with that, we can continue refining that. But I'm merging, because that unblocks other PRs (and you gave your :shipit: )

The 9.4 issue worked on travis, because that compiles without assertions :(. See #619
